return string for rails 4 compatibility
Guestfolio/ransack_ui pull request #6
Opened 2017-03-24 21:05 UTC by scottbarrow

* 	return string for rails 4 compatibility

2017-03-24 21:59 UTC, avit commented on lib/ransack_ui/ransack_overrides/helpers/form_builder.rb
> +            next nil unless foreign_klass.to_s.constantize._ransack_autocompletes_through.present?
what is this even doing... 
`.model_name` and then `.constantize`? Why not just use the `foreign_klass` directly?

2017-03-24 21:59 UTC, avit commented on lib/ransack_ui/ransack_overrides/helpers/form_builder.rb
> +          if foreign_klass && (autocomplete_source = foreign_klass.to_s.constantize._ransack_autocompletes_through rescue false)
Same here... could we just remove `.to_s.constantize`?

2017-03-24 23:49 UTC, scottbarrow commented on lib/ransack_ui/ransack_overrides/helpers/form_builder.rb
> +            next nil unless foreign_klass.to_s.constantize._ransack_autocompletes_through.present?
ah good point

2017-03-31 18:03 UTC, avit approved these changes
Looks like it'll work as expected, just some general comments.

2017-03-31 18:03 UTC, avit commented on lib/ransack_ui/ransack_overrides/helpers/form_builder.rb
> +          if foreign_klass && (autocomplete_source = foreign_klass._ransack_autocompletes_through rescue false)
Maybe pull this long `()` into its own line please, it's a bit much for an inline assignment on `if`:

`if autocomplete_source` ...

rescue should be `nil` too (like a `try`).

2017-03-31 18:03 UTC, avit commented on lib/ransack_ui/ransack_overrides/helpers/form_builder.rb
> +            next nil unless foreign_klass._ransack_autocompletes_through.present?
Autocomplete should be `nil` when not set, so shouldn't need to also call `.present?`

2017-03-31 19:22 UTC, avit requested changes

2017-03-31 19:22 UTC, avit commented on lib/ransack_ui/ransack_overrides/helpers/form_builder.rb
> +        @autocomplete_source ||= @foreign_klass && @foreign_klass._ransack_autocompletes_through
I'm not sure if the instance variable for `@foreign_klass` is going to be a safe approach.

The method `def attribute_collection_for_base(base, attributes=nil)` takes a base object: if this is different between method calls and we use it to redefine this then things could get mixed up?

2017-03-31 23:15 UTC, scottbarrow commented on lib/ransack_ui/ransack_overrides/helpers/form_builder.rb
> +        @autocomplete_source ||= @foreign_klass && @foreign_klass._ransack_autocompletes_through
right, I've added a rescue, just to keep the `_ransack_autocompletes_through` extracted but not dependent

2017-04-10 18:08 UTC, PMK9 approved these changes

2017-04-11 14:55 UTC, merged